# Smart Doc Checker - API Keys Template
# Copy this file to .streamlit/secrets.toml and add your actual keys
# DO NOT COMMIT secrets.toml TO VERSION CONTROL

[api_keys]
# Get your Gemini API key from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY = "your-gemini-api-key-here"

# Optional: OpenAI API key for future integration
OPENAI_API_KEY = "your-openai-api-key-here"

# Optional: Grok API key when available
GROK_API_KEY = "your-grok-api-key-here"

# Flexprice API key for billing integration
FLEXPRICE_API_KEY = "your-flexprice-api-key-here"
FLEXPRICE_BASE_URL = "https://api.flexprice.com/v1"

[app_settings]
DEBUG = false
MAX_FILE_SIZE = 50  # MB
MAX_FILES_PER_ANALYSIS = 5
DEFAULT_MODEL = "gemini-2.5-flash"

[pathway_settings]
# Pathway license key for real-time monitoring
PATHWAY_LICENSE_KEY = "your-pathway-license-key"
EXTERNAL_MONITOR_URL = "https://example.com/policy-updates"
MONITOR_INTERVAL = 30  # seconds

[ui_settings]
APP_TITLE = "Smart Doc Checker Agent"
COMPANY_NAME = "Your Company"
SUPPORT_EMAIL = "support@yourcompany.com"
